### PR TITLE
Adding an extension icon

### PR DESCRIPTION
**Pull request by mavaddat**
I created the logo design based on a rainbow interpretation of the Markdown logo.
Proposed logo
We can see the abstract letter "M" and the arrow ⬇ for "Down".

### CODE REVIEW

**Comment by mavaddat** [comment]
I think it is important for this great extension to have a distinctive, easily recognizable logo.

**Comment by shd101wyy** [comment]
Thank you @mavaddat ! It looks great. Before we merge this PR, may I ask if this logo is free for use or under any license? Thank you!

**Comment by mavaddat** [comment]
Yes, it is free. It is my own work.

**Review by shd101wyy — APPROVED** [review]
Approved! Thanks a lot 🙏

Will include this patch in the next version release 👍

**Pull request merged**
