### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by kachkaev**
This PR is similar to https://github.com/shd101wyy/markdown-preview-enhanced/pull/832 and https://github.com/shd101wyy/mume/pull/51 (i.e. mume's [#33 task 1](https://github.com/shd101wyy/mume/issues/33#issuecomment-368038114)).

As for the Atom extension, I temporary set `"member-ordering": false` in `tslint.json` to avoid massive member reordering in `MarkdownPreviewEnhancedView`.

### CODE REVIEW

**Comment by kachkaev** [comment]
You're right @shd101wyy, thanks for pointing that out! I removed `"declaration": true` from both PRs.

**Comment by shd101wyy** [comment]
LGTM. Thank you ;)

**Comment by kachkaev** [comment]
There's one minor remaining bit that prevents from `npm run lint` to pass – it is to do with a `<pre>` in `docs/newest.md`. Could you please clean it up in a separate commit? I'm not quite sure what's the desired end result.

screen shot 2018-04-03 at 19 37 08

**Comment by shd101wyy** [comment]
@kachkaev sure no problem. Since it's not very urgent, I will probably do it in another pull request in the future. Thank you!

**Pull request merged**
